//! Malformed-input robustness fuzzer for the public decode surface.
//!
//! The two public decode entry points — the whole-stream
//! [`oxideav_shorten::decode_stream`] driver and the constant-memory
//! [`oxideav_shorten::StreamDecoder`] iterator — take arbitrary
//! attacker-supplied bytes. Their **contract on hostile input is that
//! they return a `Result` (typically `Err`) and never panic, abort, or
//! hang**: every field width, block count, energy parameter, sub-block
//! override, and header resource field is either range-checked or
//! bounded by the finite input, so no combination of bytes should reach
//! an `unwrap`, an out-of-bounds index, an arithmetic overflow in a
//! non-checked path, an unbounded allocation, or a non-terminating
//! loop.
//!
//! This test asserts that contract by driving a large deterministic
//! corpus of malformed inputs through both entry points inside
//! [`std::panic::catch_unwind`] and asserting none of them panic. The
//! corpus is built structurally so it stresses the interesting decoder
//! states rather than only the trivial "random noise fails the magic
//! check" case:
//!
//! * **Truncations** — every prefix length of several valid baseline
//!   streams (a well-formed stream cut at an arbitrary byte, exercising
//!   mid-field / mid-block / mid-padding exhaustion, `spec/02` §1).
//! * **Bit flips** — every single-bit flip of each baseline (a valid
//!   stream with one corrupted bit, exercising every command-dispatch
//!   and field-width path reachable by a one-bit perturbation).
//! * **Byte-substitution mutations** — a deterministic PRNG overwrites
//!   K random bytes of a baseline with random values.
//! * **Random headers** — the `ajkg` magic + a version byte followed by
//!   random bytes, which reaches header parsing and (for valid version
//!   bytes) the per-block command loop with garbage fields, including
//!   over-cap resource fields the round-398 guard must reject rather
//!   than allocate against (`spec/01` §3.2/§3.4/§3.5).
//! * **Pure noise** — fully random buffers of assorted lengths.
//!
//! Clean-room provenance: the baselines are produced by the crate's own
//! [`oxideav_shorten::encode_stream`] (spec-sourced) and the corpus is
//! generated by an in-test xorshift PRNG; no external data is read.

use oxideav_shorten::{decode_stream, encode_stream, ShortenStreamHeader, StreamDecoder};

fn header(channels: u32, blocksize: u32, maxlpcorder: u32, meanblocks: u32) -> ShortenStreamHeader {
    ShortenStreamHeader {
        version: 2,
        filetype: 5, // s16lh
        channels,
        blocksize,
        maxlpcorder,
        meanblocks,
        skipbytes: 0,
    }
}

/// Deterministic xorshift64* PRNG — reproducible corpus generation with
/// no external dependency.
struct Rng(u64);

impl Rng {
    fn new(seed: u64) -> Self {
        Rng(seed | 1)
    }
    fn next_u64(&mut self) -> u64 {
        let mut x = self.0;
        x ^= x >> 12;
        x ^= x << 25;
        x ^= x >> 27;
        self.0 = x;
        x.wrapping_mul(0x2545_F491_4F6C_DD1D)
    }
    fn next_u32(&mut self) -> u32 {
        (self.next_u64() >> 32) as u32
    }
    /// Uniform-ish in `0..n` (n > 0).
    fn below(&mut self, n: usize) -> usize {
        (self.next_u64() % (n as u64)) as usize
    }
}

/// Drive both public decode entry points over `bytes`, draining the
/// streaming iterator fully. Any `Err` is fine; the only failure mode
/// this exercises is a panic (which `catch_unwind` converts into a
/// caught `Err`), a hang (bounded by the finite input + `MAX_COMMANDS`),
/// or an abort (an unbounded allocation — guarded since round 398).
fn exercise(bytes: &[u8]) {
    // Whole-stream driver.
    let _ = decode_stream(bytes);

    // Constant-memory streaming iterator: drain to completion. Each
    // command reads at least the function-code field, so a finite input
    // yields at most `input_bits` commands before `Truncated`; the
    // `MAX_COMMANDS` cap is a further backstop. A local iteration cap is
    // a belt-and-braces guard so a regression that stopped consuming
    // input can never hang this test.
    if let Ok(mut dec) = StreamDecoder::new(bytes) {
        let mut guard = 0u64;
        loop {
            guard += 1;
            assert!(
                guard < 5_000_000,
                "streaming decoder failed to terminate on a {}-byte input",
                bytes.len()
            );
            match dec.next_block() {
                Ok(Some(_)) => {}
                Ok(None) | Err(_) => break,
            }
        }
    }
}

/// A handful of valid baseline streams spanning the interesting header
/// and command-mix configurations.
fn baselines() -> Vec<Vec<u8>> {
    let mut out = Vec::new();

    // Mono, no LPC, mean estimator on, several full blocks + a tail.
    let h = header(1, 16, 0, 4);
    let s: Vec<i32> = (0..70).map(|t| ((t * 13) % 200) - 100).collect();
    out.push(encode_stream(&h, &s, &[]).expect("baseline 1 encodes"));

    // Stereo, no LPC, mean off, with a verbatim prefix.
    let h = header(2, 8, 0, 0);
    let s: Vec<i32> = (0..64).map(|t| ((t * 7) % 400) - 200).collect();
    out.push(encode_stream(&h, &s, b"RIFF").expect("baseline 2 encodes"));

    // Mono, LPC enabled (exercises the QLPC command + carry sizing).
    let h = header(1, 32, 4, 4);
    let s: Vec<i32> = (0..128)
        .map(|t| (((t as f64) * 0.30).sin() * 1000.0) as i32)
        .collect();
    out.push(encode_stream(&h, &s, &[]).expect("baseline 3 encodes"));

    // Empty stream: header immediately followed by QUIT.
    let h = header(2, 256, 0, 4);
    out.push(encode_stream(&h, &[], &[]).expect("baseline 4 encodes"));

    out
}

#[test]
fn baselines_are_self_consistent() {
    // Sanity: every baseline the fuzzer mutates must itself decode
    // cleanly, so a "no panic" pass cannot be trivially satisfied by
    // every input failing the magic check.
    for b in baselines() {
        assert!(decode_stream(&b).is_ok(), "baseline must decode");
        assert!(StreamDecoder::new(&b).is_ok(), "baseline must stream");
    }
}

#[test]
fn public_decode_never_panics_on_malformed_input() {
    // Silence the default panic hook for the duration so a *caught*
    // panic (which we assert against explicitly) does not spam the test
    // log; restore it afterwards.
    let prev = std::panic::take_hook();
    std::panic::set_hook(Box::new(|_| {}));

    let result = std::panic::catch_unwind(|| {
        let bases = baselines();
        let mut cases: u64 = 0;

        // 1. Truncations: every prefix length of each baseline.
        for b in &bases {
            for len in 0..=b.len() {
                exercise(&b[..len]);
                cases += 1;
            }
        }

        // 2. Single-bit flips of each baseline.
        for b in &bases {
            for byte_idx in 0..b.len() {
                for bit in 0..8u8 {
                    let mut m = b.clone();
                    m[byte_idx] ^= 1 << bit;
                    exercise(&m);
                    cases += 1;
                }
            }
        }

        // 3. Deterministic byte-substitution mutations.
        let mut rng = Rng::new(0xC0FF_EE12_3456_789A);
        for _ in 0..20_000 {
            let b = &bases[rng.below(bases.len())];
            let mut m = b.clone();
            if !m.is_empty() {
                let k = 1 + rng.below(6);
                for _ in 0..k {
                    let idx = rng.below(m.len());
                    m[idx] = rng.next_u32() as u8;
                }
            }
            exercise(&m);
            cases += 1;
        }

        // 4. Random headers: `ajkg` magic + version byte + random tail.
        //    Valid version bytes reach the per-block command loop and,
        //    frequently, over-cap resource fields the round-398 guard
        //    must reject without allocating.
        for _ in 0..20_000 {
            let tail_len = rng.below(48);
            let mut m = Vec::with_capacity(5 + tail_len);
            m.extend_from_slice(b"ajkg");
            m.push((rng.next_u32() % 5) as u8); // versions 0..4 (0/4 rejected, 1..3 parsed)
            for _ in 0..tail_len {
                m.push(rng.next_u32() as u8);
            }
            exercise(&m);
            cases += 1;
        }

        // 5. Pure noise of assorted lengths.
        for _ in 0..20_000 {
            let len = rng.below(64);
            let m: Vec<u8> = (0..len).map(|_| rng.next_u32() as u8).collect();
            exercise(&m);
            cases += 1;
        }

        cases
    });

    std::panic::set_hook(prev);

    match result {
        Ok(cases) => {
            // The corpus must actually be substantial — a regression
            // that made `baselines()` empty would otherwise vacuously
            // pass.
            assert!(
                cases > 50_000,
                "fuzz corpus unexpectedly small ({cases} cases)"
            );
        }
        Err(_) => panic!("a malformed input panicked the public decode surface"),
    }
}
